#!/usr/bin/env python3
#
# Copyright 2026 dobricaJankovic
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors: dobricaJankovic

"""Generate the nav2 map of a world, as a .pgm/.yaml pair."""

import argparse
import os
import sys


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--world', required=True,
                        help='Same spelling as the simulator: a .usd path, '
                             '/Isaac/... under the asset root, or a URL')
    parser.add_argument('--output', required=True,
                        help='Path without extension; .pgm and .yaml are written')
    parser.add_argument('--cell-size', type=float, default=0.05,
                        help='Metres per pixel. nav2 convention is 0.05')

    parser.add_argument('--world-z', type=float, default=0.0,
                        help="Raise the world by this much, as the simulator's "
                             '--world-z does. The two MUST agree')

    parser.add_argument('--z-min', type=float, default=0.10)
    parser.add_argument('--z-max', type=float, default=0.25)

    parser.add_argument('--bounds', type=float, default=30.0,
                        help='Half-extent in metres, or --x-min/--x-max etc.')
    parser.add_argument('--x-min', type=float)
    parser.add_argument('--x-max', type=float)
    parser.add_argument('--y-min', type=float)
    parser.add_argument('--y-max', type=float)

    args = parser.parse_args()
    for axis in ('x', 'y'):
        for end, sign in (('min', -1.0), ('max', 1.0)):
            name = '{}_{}'.format(axis, end)
            if getattr(args, name) is None:
                setattr(args, name, sign * args.bounds)
    return args


args = parse_args()

from isaacsim import SimulationApp                                   # noqa: E402

simulation_app = SimulationApp({'headless': True})

import isaacsim.core.experimental.utils.app as app_utils             # noqa: E402
import isaacsim.core.experimental.utils.stage as stage_utils         # noqa: E402
import omni.physx                                                    # noqa: E402
import omni.usd                                                      # noqa: E402
from isaacsim.core.utils.stage import add_reference_to_stage, create_new_stage  # noqa: E402

from assets import lift_world, resolve_world                        # noqa: E402

app_utils.enable_extension('isaacsim.asset.gen.omap')
simulation_app.update()

from isaacsim.asset.gen.omap.bindings import _omap                   # noqa: E402

OCCUPIED, FREE, UNKNOWN = 4, 5, 6

PGM_OCCUPIED, PGM_FREE, PGM_UNKNOWN = 0, 254, 205
OCCUPIED_THRESH, FREE_THRESH = 0.65, 0.196


def build():
    create_new_stage()
    add_reference_to_stage(usd_path=resolve_world(args.world),
                           prim_path='/World/env')
    simulation_app.update()
    while stage_utils.is_stage_loading():
        simulation_app.update()

    lift_world('/World/env', args.world_z)

    physx = omni.physx.get_physx_interface()
    physx.start_simulation()
    physx.update_simulation(1.0 / 60.0, 0.0)

    generator = _omap.Generator(physx, omni.usd.get_context().get_stage_id())
    generator.update_settings(args.cell_size, OCCUPIED, FREE, UNKNOWN)
    generator.set_transform(
        (0.0, 0.0, 0.0),
        (args.x_min, args.y_min, args.z_min),
        (args.x_max, args.y_max, args.z_max),
    )
    generator.generate2d()
    return generator


def write_map(generator):
    buffer = generator.get_buffer()
    dims = generator.get_dimensions()
    width, height = int(dims[0]), int(dims[1])
    if width <= 0 or height <= 0 or len(buffer) < width * height:
        raise RuntimeError(
            'occupancy map is {}x{} with {} cells -- nothing was '
            'mapped'.format(width, height, len(buffer)))

    value = {OCCUPIED: PGM_OCCUPIED, FREE: PGM_FREE, UNKNOWN: PGM_UNKNOWN}
    rows = []
    for row in range(height - 1, -1, -1):
        start = row * width
        rows.append(bytes(value.get(int(round(v)), PGM_UNKNOWN)
                          for v in buffer[start:start + width][::-1]))

    pgm = os.path.abspath(args.output + '.pgm')
    yaml = os.path.abspath(args.output + '.yaml')
    os.makedirs(os.path.dirname(pgm), exist_ok=True)

    with open(pgm, 'wb') as f:
        f.write(b'P5\n# generated by scripts/build_map.py\n')
        f.write('{} {}\n255\n'.format(width, height).encode())
        for row in rows:
            f.write(row)

    min_bound = generator.get_min_bound()
    with open(yaml, 'w') as f:
        f.write('image: {}\n'.format(os.path.basename(pgm)))
        f.write('mode: trinary\n')
        f.write('resolution: {}\n'.format(args.cell_size))
        f.write('origin: [{:.4f}, {:.4f}, 0.0000]\n'.format(
            min_bound[0], min_bound[1]))
        f.write('negate: 0\n')
        f.write('occupied_thresh: {}\n'.format(OCCUPIED_THRESH))
        f.write('free_thresh: {}\n'.format(FREE_THRESH))

    occupied = sum(r.count(PGM_OCCUPIED) for r in rows)
    free = sum(r.count(PGM_FREE) for r in rows)
    print('map: {}x{} px at {} m/px, origin [{:.3f}, {:.3f}]'.format(
        width, height, args.cell_size, min_bound[0], min_bound[1]), flush=True)
    print('     world {} raised {:g} m, slice z={}..{}'.format(
        args.world, args.world_z, args.z_min, args.z_max), flush=True)
    print('     {} occupied, {} free, {} unknown'.format(
        occupied, free, width * height - occupied - free), flush=True)
    print('     {}'.format(yaml), flush=True)

    if occupied == 0:
        raise RuntimeError(
            'no occupied cells: the slice z={}..{} met no collision geometry. '
            'Check the world has colliders and the slice is at lidar '
            'height.'.format(args.z_min, args.z_max))


def main():
    write_map(build())


if __name__ == '__main__':
    status = 0
    try:
        main()
    except Exception:                                    # noqa: BLE001
        import traceback
        traceback.print_exc()
        status = 1
    finally:
        sys.stdout.flush()
        sys.stderr.flush()
        os._exit(status)
